// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA33Bnhr2hGoBScpuWcjoC19om36YjnpSY',
    appId: '1:287722549923:web:0a0d0b8b0a9306de758516',
    messagingSenderId: '287722549923',
    projectId: 'cricbuzz-b60da',
    authDomain: 'cricbuzz-b60da.firebaseapp.com',
    storageBucket: 'cricbuzz-b60da.appspot.com',
    measurementId: 'G-QLE49SY6N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGS7WPG8Fz-m4bUr14wh99qXQJZPKKaKw',
    appId: '1:287722549923:android:d4611e10f38354aa758516',
    messagingSenderId: '287722549923',
    projectId: 'cricbuzz-b60da',
    storageBucket: 'cricbuzz-b60da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfaWqmCR1dQlmkwii4kE9octI8-YG2-rw',
    appId: '1:287722549923:ios:beac9b468cd73a35758516',
    messagingSenderId: '287722549923',
    projectId: 'cricbuzz-b60da',
    storageBucket: 'cricbuzz-b60da.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfaWqmCR1dQlmkwii4kE9octI8-YG2-rw',
    appId: '1:287722549923:ios:55a06ae3bc2e857c758516',
    messagingSenderId: '287722549923',
    projectId: 'cricbuzz-b60da',
    storageBucket: 'cricbuzz-b60da.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
